### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by JoeKrueger** [JesseBilsten/refusal-dice#1]
Krueger@sbcglobal.net 

We are interested in where you learned your Refusal rules.

Thanks!

Joe Krueger

**Comment by JesseBilsten** [comment]
Hi Joe!

I sent you an email, but for documentation purposes, the rules I have here are from the San Luis Obispo Country Club's dice room. I'm not 100% sure who taught them to this group, but I know some of the players mentioned Monterey as the source.
